//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIT_PR6._2_Balashova_Petrov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserAuthDBEntities : DbContext
    {
        private static UserAuthDBEntities _context;
        public UserAuthDBEntities()
            : base("name=UserAuthDBEntities")
        {
        }
        public static UserAuthDBEntities GetContext()
        {
            if (_context == null)
                _context = new UserAuthDBEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
    }
}
