//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIT_PR6._2_Balashova_Petrov
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Logins { get; set; }
        public string Passwords { get; set; }
        public string Roles { get; set; }
        public string FIO { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Photo { get; set; }
    }
}
